### ISSUE TITLE
Profile Route in Auth

### ISSUE THREAD

**Issue by priyanshunayan** [vsrnitp/privateRouting#1]
Why is Profile route in Auth Section? It should be in users route.

**Comment by vsrnitp** [comment]
Yes , it should be.... i havent designed my folder structure in scalable way...

**Comment by priyanshunayan** [comment]
May i do it?

**Comment by vsrnitp** [comment]
Yep

**Comment by priyanshunayan** [comment]
Solved via Query params. As setting headers  is not supported in HTTP redirect.
